################################################################################
#  ▗▄▄▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖▗▄▄▄▖ ▗▄▄▖ ▗▄▄▖                                         # 
# ▐▌   ▐▌ ▐▌▐▛▚▖▐▌▐▌     █  ▐▌   ▐▌                                            # 
# ▐▌   ▐▌ ▐▌▐▌ ▝▜▌▐▛▀▀▘  █  ▐▌▝▜▌ ▝▀▚▖                                         #
# ▝▚▄▄▖▝▚▄▞▘▐▌  ▐▌▐▌   ▗▄█▄▖▝▚▄▞▘▗▄▄▞▘                                         #
#                                                                              #
################################################################################
# patorjk.com [RubiFont]
[window.padding]
    x = 0
    y = 0

[window]
    decorations = "none"
    dynamic_title = false
    opacity = 1.0

[scrolling]
    history = 10000
    multiplier = 3

[cursor.style]
    shape = "Beam"
    blinking = "On"
################################################################################
# ▗▄▄▄▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖▗▄▄▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖▗▄▄▄▖ ▗▄▄▖                          #
# ▐▌   ▐▌ ▐▌▐▛▚▖▐▌  █ ▐▌   ▐▌ ▐▌▐▛▚▖▐▌▐▌     █  ▐▌                             #
# ▐▛▀▀▘▐▌ ▐▌▐▌ ▝▜▌  █ ▐▌   ▐▌ ▐▌▐▌ ▝▜▌▐▛▀▀▘  █  ▐▌▝▜▌                          #
# ▐▌   ▝▚▄▞▘▐▌  ▐▌  █ ▝▚▄▄▖▝▚▄▞▘▐▌  ▐▌▐▌   ▗▄█▄▖▝▚▄▞▘                          #
#                                                                              #
#                                                                              #
################################################################################
[font.normal]
    #family = "0xProtoNerdFont"
    family = "TerminessNerdFont"
    #family = "ComicShannsMonoNerdFont"
    #family = "UbuntuMonoNerdFont"
    #family = "IosevkaTermSlabNerdFont"
    #family = "ProggyCleanCENerdFont"
    #style = "bold"

[font]
    size =    9.0 #TerminessNerdFont
    #size =  12.0 #ProggyCleanNerdFont
    #size =  24.0 #ProggyCleanNerdFont
    #size =  14.0 #IosevkaTermSlabNerdFont
    #size =  12.5 #0xProtoNerdFont

[font.offset]
    x =  0
    y = -3
################################################################################
#  ▗▄▄▖ ▗▄▖ ▗▖    ▗▄▖ ▗▄▄▖  ▗▄▄▖ ▗▄▄▖▗▖ ▗▖▗▄▄▄▖▗▖  ▗▖▗▄▄▄▖ ▗▄▄▖                #
# ▐▌   ▐▌ ▐▌▐▌   ▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌   ▐▌ ▐▌▐▌   ▐▛▚▞▜▌▐▌   ▐▌                   #
# ▐▌   ▐▌ ▐▌▐▌   ▐▌ ▐▌▐▛▀▚▖ ▝▀▚▖▐▌   ▐▛▀▜▌▐▛▀▀▘▐▌  ▐▌▐▛▀▀▘ ▝▀▚▖                #
# ▝▚▄▄▖▝▚▄▞▘▐▙▄▄▖▝▚▄▞▘▐▌ ▐▌▗▄▄▞▘▝▚▄▄▖▐▌ ▐▌▐▙▄▄▖▐▌  ▐▌▐▙▄▄▖▗▄▄▞▘                #
#                                                                              #
#                                                                              #
################################################################################
[env]
TERM = "xterm-256color"

[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#cd0000'
green   = '#00cd00'
yellow  = '#cdcd00'
blue    = '#0000ee'
magenta = '#cd00cd'
cyan    = '#00cdcd'
white   = '#e5e5e5'

# Bright colors
[colors.bright]
black   = '#7f7f7f'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#5c5cff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'
